Add typecheck test and fix types

diff --git a/bin/tests b/bin/tests
--- a/bin/tests
+++ b/bin/tests
@@ -8,6 +8,14 @@ then
   exit 1
 fi
 
+echo "------------- Types -------------"
+
+if ! npm run typecheck
+then
+  echo "Type checking failed"
+  exit 1
+fi
+
 echo "------------- Build -------------"
 
 if ! npm run build
